const dogData = [
    "Loves belly rubs",
    "Picky eater",
    "Loves napping",
    "Loves making dog friends",
    "Energetic",
    "Eager-to-please",
    "Easy-to-train",
    "Faithful",
    "Family-friendly",
    "Fast",
    "Fiercely loyal",
    "Fluffy",
    "Friendly",
    "Gentle",
    "Goofy",
    "Happy",
    "Snuggly",
    "Loving",
    "Stubborn",
    "Crate-trained",
    "Healthy",
    "Quirky",
    "Potty-trained",
    "Smart",
    "Smelly",
    "Needy",
    "Clumsy",
    "Favorite food: chicken",
    "Always ready to go on a walk",
    "Always ready to play",
    "Always there to give snuggles",
    "Greets you at the door every day",
    "Good with kids",
    "Sock thief",
    "Shoe thief",
    "Thinks she's human",
    "Easy going",
    "Adventurous",
    "Attention seeker",
    "Gets jealous easily",
    "Puppy eyes game strong",
    "Will win in a staring contest"
]

export default dogData;